package com.acc.datos.laura.hibernate_project.POJOS;// default package
// Generated 24 nov 2025, 10:22:24 by Hibernate Tools 6.6.33.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * com.acc.datos.laura.hibernate_project.POJOS.Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
    ,catalog="proyecto_orm"
)
public class Departamento  implements java.io.Serializable {


     private Integer idDepto;
     private Sede sede;
     private String nomDepto;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Departamento() {
    }

	
    public Departamento(Sede sede, String nomDepto) {
        this.sede = sede;
        this.nomDepto = nomDepto;
    }
    public Departamento(Sede sede, String nomDepto, Set<Empleado> empleados) {
       this.sede = sede;
       this.nomDepto = nomDepto;
       this.empleados = empleados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_depto", unique=true, nullable=false)
    public Integer getIdDepto() {
        return this.idDepto;
    }
    
    public void setIdDepto(Integer idDepto) {
        this.idDepto = idDepto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede", nullable=false)
    public Sede getSede() {
        return this.sede;
    }
    
    public void setSede(Sede sede) {
        this.sede = sede;
    }

    
    @Column(name="nom_depto", nullable=false, length=32)
    public String getNomDepto() {
        return this.nomDepto;
    }
    
    public void setNomDepto(String nomDepto) {
        this.nomDepto = nomDepto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


